import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const dinBold = localFont({
  src: '../../public/fonts/DIN-Bold.otf',
  display: 'swap',
  variable: '--font-din-bold',
})

const dinProCond = localFont({
  src: '../../public/fonts/DINPro-Cond.otf',
  display: 'swap',
  variable: '--font-din-pro-cond',
})

const dinProCondBlack = localFont({
  src: '../../public/fonts/DINPro-CondBlack.otf',
  display: 'swap',
  variable: '--font-din-pro-cond-black',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dinBold.variable} ${dinProCond.variable} ${dinProCondBlack.variable}`}>
      <body>{children}</body>
    </html>
  );
}
